"""The real validation routine is exercised only against temporary databases."""
import sys
from pathlib import Path

import pytest
from alembic import command
from sqlalchemy import text

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))
from local_database import validate_database, REQUIRED_TABLES


def test_valid_database_preserves_data(migrated):
    engine, config = migrated
    with engine.begin() as connection:
        connection.execute(text("INSERT INTO companies (name,created_at,updated_at) VALUES ('Preservar',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)"))
    report = {}
    validate_database(config.attributes['database_url'], report)
    assert report['status'] == 'passed'
    assert report['current_heads'] == report['expected_heads'] == ['0003']
    assert REQUIRED_TABLES <= set(report['tables'])
    with engine.connect() as connection:
        assert connection.execute(text('SELECT name FROM companies')).scalar_one() == 'Preservar'


@pytest.mark.parametrize('table', sorted(REQUIRED_TABLES))
def test_stamped_database_missing_table_fails(migrated, table):
    engine, config = migrated
    with engine.begin() as connection:
        connection.execute(text(f'DROP TABLE {table}'))
    report = {}
    with pytest.raises(RuntimeError, match=table):
        validate_database(config.attributes['database_url'], report)
    assert report['status'] == 'failed'


def test_normal_upgrade(migrated):
    _, config = migrated
    command.downgrade(config, '0002')
    report = {}
    validate_database(config.attributes['database_url'], report)
    assert report['current_heads'] == ['0003']


def test_absent_database_is_not_created(tmp_path):
    path = tmp_path / 'absent.db'
    with pytest.raises(RuntimeError, match='Banco local ausente'):
        validate_database(f'sqlite:///{path}', {})
    assert not path.exists()


def test_runner_fails_before_tests_on_inconsistent_database(migrated, tmp_path, monkeypatch):
    import importlib.util
    import json
    engine, config = migrated
    with engine.begin() as connection:
        connection.execute(text('DROP TABLE period_adjustments'))
    script = Path(__file__).resolve().parents[2] / 'scripts/validate.py'
    spec = importlib.util.spec_from_file_location('validation_runner', script)
    runner = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(runner)
    monkeypatch.setattr(runner, 'DATABASE_URL', config.attributes['database_url'])
    monkeypatch.setattr(runner, 'ROOT', tmp_path)
    (tmp_path / 'backend').mkdir()
    monkeypatch.setattr(runner.subprocess, 'check_output', lambda *args, **kwargs: '')
    monkeypatch.setattr(runner.subprocess, 'run', lambda *args, **kwargs: None)
    monkeypatch.chdir(tmp_path)
    assert runner.main() == 1
    report = json.loads(next((tmp_path / 'validation-results').glob('*.json')).read_text())
    assert report['status'] == 'failed'
    assert report['local_database']['status'] == 'failed'
    assert report['steps'] == []
    assert 'period_adjustments' in report['error']


def test_stamped_database_missing_column_fails(migrated):
    from alembic.util.exc import AutogenerateDiffsDetected
    engine, config = migrated
    with engine.begin() as connection:
        connection.execute(text('ALTER TABLE transactions DROP COLUMN observation'))
    with pytest.raises(AutogenerateDiffsDetected):
        validate_database(config.attributes['database_url'], {})
