import { test, expect } from "@playwright/test";
import type { Page } from "@playwright/test";
async function setup(page: Page) {
  await page.goto("/");
  await page.getByRole("button", { name: "Começar minha DRE" }).click();
  await page.getByLabel("Nome da empresa").fill("Empresa Teste DRE");
  await page.getByLabel("Segmento").fill("Serviços");
  await page.getByLabel("Mês", { exact: true }).selectOption("8");
  await page.getByLabel("Ano", { exact: true }).fill("2026");
  await page.getByRole("button", { name: "Continuar", exact: true }).click();
  await expect(page.getByRole("heading", { name: "DRE — Agosto/2026" })).toBeVisible();
  return new URL(page.url()).searchParams.get("period");
}
async function add(page: Page, direction: "receita" | "saída", description: string, amount: string, category: string, sub?: string, date = "2026-08-10") {
  await page.getByRole("button", { name: `Adicionar ${direction}`, exact: true }).click();
  const dialog = page.getByRole("dialog", { name: `Adicionar ${direction}`, exact: true });
  await dialog.getByLabel("Data", { exact: true }).fill(date);
  await dialog.getByLabel("Competência", { exact: true }).fill("2026-08");
  await dialog.getByLabel("Descrição", { exact: true }).fill(description);
  await dialog.getByLabel("Valor", { exact: true }).fill(amount);
  await dialog.getByLabel("Categoria", { exact: true }).selectOption(category);
  if (sub) await dialog.getByLabel("Subcategoria", { exact: true }).selectOption({ label: sub });
  await dialog.getByRole("button", { name: "Salvar", exact: true }).click();
  await expect(dialog).not.toBeVisible();
}

test("four required transactions, exact totals, isolation and persistence", async ({ page, request }) => {
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  const id = await setup(page);
  await page.getByRole("button", { name: "Começar pelas Receitas" }).click();
  await add(page, "receita", "Mensalidades", "100000", "REVENUE_RECURRING", undefined, "2026-08-05");
  await expect(page.getByRole("cell", { name: "Mensalidades", exact: true })).toBeVisible();
  await expect(page.locator(".summary")).toContainText("R$ 100.000,00");
  await page.getByRole("button", { name: "Saídas", exact: true }).click();
  await add(page, "saída", "Link IP", "20000", "COST", "Infraestrutura");
  await add(page, "saída", "Google Workspace", "1500", "EXPENSE", "Tecnologia");
  await add(page, "saída", "Servidor", "30000", "INVESTMENT", "Equipamentos");
  await expect(page.locator(".summary")).toContainText("R$ 51.500,00");
  await expect(page.getByRole("cell", { name: "Mensalidades", exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole("heading", { name: "DRE — Agosto/2026" })).toBeVisible();
  await expect(page.getByRole("progressbar", { name: "Receitas" })).toHaveAttribute("aria-valuenow", "100");
  await expect(page.getByRole("progressbar", { name: "Saídas" })).toHaveAttribute("aria-valuenow", "100");
  await expect(page.getByText("Calculada", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "DRE", exact: true })).toBeEnabled();
  const revenues = (await (await request.get(`/api/periods/${id}/revenues`)).json()).data;
  const expenses = (await (await request.get(`/api/periods/${id}/expenses`)).json()).data;
  expect(revenues).toHaveLength(1); expect(expenses).toHaveLength(3);
  expect(revenues[0]).toMatchObject({ description: "Mensalidades", amount: "100000.00", direction: "IN" });
  expect(expenses.find((t: { description: string }) => t.description === "Servidor")).toMatchObject({ amount: "30000.00", dre_effect: "NO_EFFECT", include_in_dre: false });
  await page.getByRole("button", { name: "Saídas", exact: true }).click();
  for (const description of ["Link IP", "Google Workspace", "Servidor"]) await expect(page.getByRole("cell", { name: description, exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/m2-expenses.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test("manual revenue edit, filters, search, guided mode and confirmed delete", async ({ page, request }) => {
  const id = await setup(page);
  await page.getByRole("button", { name: "Receitas", exact: true }).click();
  await add(page, "receita", "Receita inicial", "0,10", "UNDEFINED");
  await expect(page.getByRole("cell", { name: "Não classificado", exact: true })).toBeVisible();
  await page.getByLabel("Filtrar status").selectOption("CONFIRMED");
  await expect(page.getByText("Nenhum lançamento encontrado.")).toBeVisible();
  await page.getByLabel("Filtrar status").selectOption("PENDING");
  await page.getByRole("button", { name: "Editar", exact: true }).click();
  const editor = page.getByRole("dialog", { name: "Editar receita", exact: true });
  await expect(editor.getByText("Data: quando a movimentação ocorreu.", { exact: false })).toBeVisible();
  await editor.getByLabel("Descrição", { exact: true }).fill("Receita revisada");
  await editor.getByLabel("Valor", { exact: true }).fill("0,20");
  await editor.getByLabel("Categoria", { exact: true }).selectOption("FINANCIAL_REVENUE");
  await editor.getByRole("button", { name: "Salvar", exact: true }).click();
  await page.getByLabel("Filtrar status").selectOption("ALL");
  await expect(page.getByRole("cell", { name: "Receita revisada" })).toBeVisible();
  await page.getByLabel("Buscar por descrição").fill("inexistente");
  await expect(page.getByText("Nenhum lançamento encontrado.")).toBeVisible();
  await page.getByLabel("Buscar por descrição").fill("revisada");
  await expect(page.getByRole("cell", { name: "Receita revisada" })).toBeVisible();
  const rows = (await (await request.get(`/api/periods/${id}/revenues`)).json()).data;
  expect(rows[0]).toMatchObject({ original_description: "Receita inicial", description: "Receita revisada", amount: "0.20", dre_effect: "FINANCIAL_REVENUE" });
  await page.getByRole("button", { name: "Configurações" }).click();
  await page.getByRole("switch", { name: "Modo Guiado" }).click();
  await expect(page.getByRole("switch")).toHaveAttribute("aria-checked", "false");
  await page.getByRole("button", { name: "Receitas", exact: true }).click();
  await page.getByRole("button", { name: "Editar", exact: true }).click();
  await expect(page.getByRole("dialog").locator(".help")).toHaveCount(0);
  await page.getByRole("button", { name: "Cancelar", exact: true }).click();
  await page.getByRole("button", { name: "Excluir", exact: true }).click();
  await page.getByRole("button", { name: "Cancelar", exact: true }).click();
  await expect(page.getByRole("cell", { name: "Receita revisada" })).toBeVisible();
  await page.getByRole("button", { name: "Excluir", exact: true }).click();
  await page.getByRole("button", { name: "Confirmar exclusão" }).click();
  await expect(page.getByText("Nenhum lançamento encontrado.")).toBeVisible();
  expect((await (await request.get(`/api/periods/${id}/revenues`)).json()).data).toEqual([]);
});

test("custom subcategory inline, settings edit/archive and persistence", async ({ page }) => {
  await setup(page);
  await page.getByRole("button", { name: "Saídas", exact: true }).click();
  await page.getByRole("button", { name: "Adicionar saída" }).click();
  const editor = page.getByRole("dialog", { name: "Adicionar saída", exact: true });
  await editor.getByLabel("Descrição", { exact: true }).fill("Despesa personalizada");
  await editor.getByLabel("Valor", { exact: true }).fill("250,99");
  await editor.getByLabel("Categoria", { exact: true }).selectOption("EXPENSE");
  await editor.getByRole("button", { name: "+ Criar nova subcategoria", exact: true }).click();
  const sub = page.getByRole("dialog", { name: "Nova subcategoria", exact: true });
  await sub.getByLabel("Nome", { exact: true }).fill("Ferramentas internas");
  await expect(sub.getByLabel("Categoria principal")).toBeDisabled();
  await sub.getByRole("button", { name: "Salvar subcategoria" }).click();
  await expect(sub).not.toBeVisible();
  await expect(editor.getByLabel("Subcategoria", { exact: true }).locator("option:checked")).toHaveText("Ferramentas internas");
  await editor.getByRole("button", { name: "Salvar", exact: true }).click();
  await page.reload();
  await page.getByRole("button", { name: "Saídas", exact: true }).click();
  await expect(page.getByRole("cell", { name: "Ferramentas internas" })).toBeVisible();
  await page.getByRole("button", { name: "Configurações" }).click();
  let row = page.getByRole("row").filter({ hasText: "Ferramentas internas" });
  await row.getByRole("button", { name: "Editar" }).click();
  await page.getByRole("dialog").getByLabel("Nome", { exact: true }).fill("Ferramentas da equipe");
  await page.getByRole("button", { name: "Salvar subcategoria" }).click();
  row = page.getByRole("row").filter({ hasText: "Ferramentas da equipe" });
  await row.getByRole("button", { name: "Arquivar" }).click();
  await page.getByRole("button", { name: "Confirmar arquivamento" }).click();
  await expect(row.getByRole("cell", { name: "Arquivada", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Saídas", exact: true }).click();
  await expect(page.getByRole("cell", { name: "Ferramentas da equipe" })).toBeVisible();
  await page.getByRole("button", { name: "Adicionar saída" }).click();
  await editor.getByLabel("Categoria", { exact: true }).selectOption("EXPENSE");
  await expect(editor.getByLabel("Subcategoria", { exact: true }).locator("option").filter({ hasText: "Ferramentas da equipe" })).toHaveCount(0);
});

test("friendly form validation, API error, double submit and partial progress", async ({ page }) => {
  await setup(page);
  await page.getByRole("button", { name: "Receitas", exact: true }).click();
  await page.getByRole("button", { name: "Adicionar receita" }).click();
  const editor = page.getByRole("dialog", { name: "Adicionar receita", exact: true });
  await editor.getByLabel("Descrição", { exact: true }).fill("   ");
  await editor.getByLabel("Valor", { exact: true }).fill("0");
  await editor.getByRole("button", { name: "Salvar", exact: true }).click();
  await expect(editor.getByRole("alert")).toHaveText("Informe uma descrição válida.");
  await editor.getByLabel("Descrição", { exact: true }).fill("Revisar receita");
  await editor.getByRole("button", { name: "Salvar", exact: true }).click();
  await expect(editor.getByRole("alert")).toContainText("Informe um valor maior que zero");
  await editor.getByLabel("Valor", { exact: true }).fill("10,50");
  let posts = 0;
  await page.route("**/api/periods/*/transactions", async route => {
    posts++;
    if (posts === 1) await route.fulfill({ status: 409, json: { error: { code: "PERIOD_CLOSED", message: "Este período está fechado e não pode ser alterado.", details: {} } } });
    else await route.continue();
  });
  await editor.getByRole("button", { name: "Salvar", exact: true }).click();
  await expect(editor.getByRole("alert")).toHaveText("Este período está fechado e não pode ser alterado.");
  await editor.getByRole("button", { name: "Salvar", exact: true }).evaluate((button: HTMLButtonElement) => { button.click(); button.click(); });
  await expect(editor).not.toBeVisible();
  expect(posts).toBe(2);
  await add(page, "receita", "Classificada", "0,10", "REVENUE_SERVICE");
  await expect(page.locator(".summary")).toContainText("R$ 10,60");
  await page.getByRole("button", { name: "Visão Geral" }).click();
  await expect(page.getByRole("progressbar", { name: "Receitas" })).toHaveAttribute("aria-valuenow", "50");
});
